[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.40.0"
lune = "filiptibell/lune@0.8.9"
rojo = "rojo-rbx/rojo@7.4.4"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
selene = "kampfkarren/selene@0.28.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.2"
