[package]
name = "howmanysmall/janitor"
description = "A garbage collector object implementation for Roblox, featuring support for custom cleanup methods, Promises, and instance linking."
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.13.16"
exclude = ["example", "docs", "Packages", ".moonwave", "build", "pages", "test"]

[dependencies]
